apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-app
  labels:
    app: front-end-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: front-end-app
    spec:
      containers:
      - image: rajeev1391/capston_b1
        imagePullPolicy: Always
        name: front-end-app
        ports:
        - containerPort: 80
          protocol: TCP
